spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.189.128/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  freemarker:
    suffix: .ftl   #设定ftl文件路径
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: /static/**
server:
  port: 8080
  servlet:
    context-path: /sell

wechat:
  mpAppId: wx2b7e8a3787c01e65
  mpAppSecret: 7fbab8be85b762cb4a40bf04cbe5e803
  mchId:
  key-path:
  mch-key:
  notify-url: http://sellwechat.nat100.top/sell/pay/notify
  template-id:
    orderStatus: ydnOXKtlqA6gb_--q_CCEDwVpfyUbGNryw3SABnZW6E

project-url:
  wechat-mp-authorize:  http://sellwechat.nat100.top
  wechat-open-authorize:  http://sellwechat.nat100.top
  sell:  http://sellwechat.nat100.top

